debug_mode: false
local: false
#debug_mode: true
server:
  host: 0.0.0.0
  access_log: true
  workers: 8
  port: 5004
  ssl_key: /home/ray/Workspace/file/cert/www.guijutech.com.key
  ssl_cert: /home/ray/Workspace/file/cert/www.guijutech.com.pem
  client_access_url: https://www.guijutech.com/service
  ssl: false
  msg_expire_secs: 6000
redis:
  host: 127.0.0.1
  port: 6379
  redis_mq: 11
storage_dirpath:
  user_dir: outputs/img2img-images/user_history
  hires_dir: outputs/img2img-images/user_history
  lora_model_dir: /home/ray/Workspace/file/素材/头像/224/
  lora_place_dir: /home/ray/Workspace/file/素材/背景/224/
mq_name: debug_queue
wechatpay:
  # 微信支付商户号，服务商模式下为服务商户号，即官方文档中的sp_mchid。
  MCHID: '1648762150'
  # 商户证书私钥，此文件不要放置在下面设置的CERT_DIR目录里。
  PRIVATE_KEY: /home/ray/Documents/wechat/material/1648762150_20230811_cert/apiclient_key.pem
  # 商户证书序列号
  CERT_SERIAL_NO: 7D16348EBB61946FA3808AA6B8936BC16085A402
  # API v3密钥， https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay3_2.shtml
  APIV3_KEY: 'xUhH4VLln5XxyU0MYjL86y2sdu7pbtHO'
  # APPID，应用ID，服务商模式下为服务商应用ID，即官方文档中的sp_appid，也可以在调用接口的时候覆盖。
  APPID: 'wx4cc6a80c7057e291'
  # 回调地址，也可以在调用接口的时候覆盖。
  NOTIFY_URL: http://127.0.0.1:5004/notify'
  # 微信支付平台证书缓存目录，初始调试的时候可以设为None，首次使用确保此目录为空目录。
  CERT_DIR: ./cert
  # 接入模式：False=直连商户模式，True=服务商模式。
  PARTNER_MODE: false
  # 代理设置，None或者{"https": "http://10.10.1.10:1080"}，详细格式参见[https://requests.readthedocs.io/en/latest/user/advanced/#proxies](https://requests.readthedocs.io/en/latest/user/advanced/#proxies)
  PROXY: null
wechatlogin:
  appid: wx8b7f856da1e0485c
  secret: 549d9da20952e20ed5cd86ec81303640
supabase:
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZGpid2draGNlYW14eWl4bnBzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4ODcyNTExMCwiZXhwIjoyMDA0MzAxMTEwfQ.KbWdkdElmB0BpOgtPWFSmB5F6vq9Bjo7PyTVQAiHwGU"
  url: "https://dcdjbwgkhceamxyixnps.supabase.co"
