debug_mode: false
local: false
#debug_mode: true
server:
  host: 0.0.0.0
  access_log: true
  workers: 8
  port: 5004
  ssl_key: /home/ray/Workspace/file/cert/www.guijutech.com.key
  ssl_cert: /home/ray/Workspace/file/cert/www.guijutech.com.pem
  client_access_url: https://www.guijutech.com/service
  ssl: false
  msg_expire_secs: 6000
redis:
  host: 127.0.0.1
  port: 6379
  redis_mq: 11
storage_dirpath:
  user_storage: outputs/img2img-images/user_storage
  user_upload: outputs/img2img-images/user_upload
  user_account_avatar: outputs/user_account_avatar
  user_facer_upload: outputs/img2img-images/user_facer_upload
mq_name: debug_queue
wechatpay:
  # 微信支付商户号，服务商模式下为服务商户号，即官方文档中的sp_mchid。
  MCHID: '1648762150'
  # 商户证书私钥，此文件不要放置在下面设置的CERT_DIR目录里。
  PRIVATE_KEY: /home/zzg/weichat/material/1648762150_20230811_cert/apiclient_key.pem
  # 商户证书序列号
  CERT_SERIAL_NO: 7D16348EBB61946FA3808AA6B8936BC16085A402
  # API v3密钥， https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay3_2.shtml
  APIV3_KEY: 'xUhH4VLln5XxyU0MYjL86y2sdu7pbtHO'
  # APPID，应用ID，服务商模式下为服务商应用ID，即官方文档中的sp_appid，也可以在调用接口的时候覆盖。
  APPID: 'wx4cc6a80c7057e291'
  # 回调地址，也可以在调用接口的时候覆盖。
  NOTIFY_URL: http://127.0.0.1:5004/notify'
  # 微信支付平台证书缓存目录，初始调试的时候可以设为None，首次使用确保此目录为空目录。
  CERT_DIR: ./cert
  # 接入模式：False=直连商户模式，True=服务商模式。
  PARTNER_MODE: false
  # 代理设置，None或者{"https": "http://10.10.1.10:1080"}，详细格式参见[https://requests.readthedocs.io/en/latest/user/advanced/#proxies](https://requests.readthedocs.io/en/latest/user/advanced/#proxies)
  PROXY: null
wechatlogin:
  appid: wx8b7f856da1e0485c
  secret: 549d9da20952e20ed5cd86ec81303640
googlelogin:
  client_id: '51336041422-d1a9ssmmhauk16n4mc9a21mmbv36h604.apps.googleusercontent.com'
#  client_id: '714423616983-8l6ttvp7f7nhsqg4t5q4k56onj2m2pf6.apps.googleusercontent.com'
facebooklogin:
  app_id: 1135974444063887
  secret: 5e52a95df62d02accfc40ae40e7cf97f
linelogin:
  token_url: 'https://api.line.me/oauth2/v2.1/token'
  verify_url: "https://api.line.me/oauth2/v2.1/verify"
  redirect_uri: "https://ingjp.jp/service/line/login"
  client_id: 2002220773
  client_secret: 858c2de760633372d0f1e14e2ba0a664
#  code_verifier: 858c2de760633372d0f1e14e2ba0a664
paypal:
#  client_id: 'AcOS-pWypZ1RaAiDtVKgdZrDQswef6T5BnTAnZ9mS6CNvtGGbhPOMhZndF071NsphTy36dhshHDt1Y3e'
#  client_secret: 'EBnWq7Wr5gi54nSwpSpvbKRzecgi8X7G73Xy7SO_lz1HJP9CAbKU4Jw5pSRYUG3KOn9yJz6QC6b8pcaB'
#  base_url: 'https://api-m.sandbox.paypal.com'
  client_id: 'AZDhKqULcx0KLEAdgQWc_OcUx-w-LYkVmBzpERrm5_AsoWhaywYPBMaJ5LsSfAFlVUSvmAqydzw3zsdw'
  client_secret: 'EEf6vgyse9IUUYeSaK2k6Phb8CXAdWU9c34HqhlDR_259zs76HUIJ79SMApSrZooJo-kI4exOjf2rQgu'
  base_url: 'https://api-m.paypal.com'
  sub_v1: 'PROD-7FD03536XW314484W'
  sub_v2: 'PROD-7FD03536XW314484W'
  sub_v3: 'PROD-7FD03536XW314484W'
supabase:
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogInNlcnZpY2Vfcm9sZSIsCiAgImlzcyI6ICJzdXBhYmFzZSIsCiAgImlhdCI6IDE2OTU4MzA0MDAsCiAgImV4cCI6IDE4NTM2ODMyMDAKfQ.QanqKpEYyjqgvl1ElcWw7JJAvUEzIC0e0w1pFfPOITE"
#  url: "https://www.guijutech.com:8888"
  url: "http://127.0.0.1:8888"
aliyun:
  sms:
    access_key_id: "LTAI5tHqAUujrdmH8yQCw3N4"
    access_key_secret: "CZ0H8ts8FTZblgymKIGNt5rdQj5DON"
    template_code: "SMS_463945297"
    global_template_code: "SMS_464540310"
#    template_code: "SMS_290885121"
http_proxy: "http://127.0.0.1:1095"
payment:
  point_price:
    USD: 0.02
    RMB: 0.1
